### ISSUE TITLE
read() missing 2 required positional arguments: 'xlsx_parh' and 'doc_type'

### ISSUE THREAD

**Issue by kvasnikoff** [YaSlavar/parser_mirea#1]
Привет! Попытался запустить проект у себя: выдает ошибку :(
<img width="1105" alt="Screenshot 2020-03-06 at 15 01 26" src="https://user-images.githubusercontent.com/40367440/76082038-800bc700-5fbb-11ea-9e9e-cda4eab399d0.png">

**Comment by YaSlavar** [comment]
Привет, спасибо за сообщение, попаравлю main файл, напишите пожалуйста на почту , ya.slavar@yandex.ru
